// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: contact_info.sql

package db

import (
	"context"
)

const createContactInfo = `-- name: CreateContactInfo :one
INSERT INTO contact_info (
  user_id,
  email,
  phone,
  address,
  city,
  state,
  zip,
  country
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, user_id, email, phone, address, city, state, zip, country, is_deleted, created_at, updated_at, deleted_at
`

type CreateContactInfoParams struct {
	UserID  int64   `db:"user_id" json:"user_id"`
	Email   *string `db:"email" json:"email"`
	Phone   *string `db:"phone" json:"phone"`
	Address *string `db:"address" json:"address"`
	City    *string `db:"city" json:"city"`
	State   *string `db:"state" json:"state"`
	Zip     *string `db:"zip" json:"zip"`
	Country *string `db:"country" json:"country"`
}

func (q *Queries) CreateContactInfo(ctx context.Context, arg CreateContactInfoParams) (ContactInfo, error) {
	row := q.db.QueryRow(ctx, createContactInfo,
		arg.UserID,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Country,
	)
	var i ContactInfo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Country,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserContactInfo = `-- name: GetUserContactInfo :one
SELECT id, user_id, email, phone, address, city, state, zip, country, is_deleted, created_at, updated_at, deleted_at FROM contact_info
WHERE user_id = $1 AND is_deleted = false
LIMIT 1
`

func (q *Queries) GetUserContactInfo(ctx context.Context, userID int64) (ContactInfo, error) {
	row := q.db.QueryRow(ctx, getUserContactInfo, userID)
	var i ContactInfo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Country,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateContactInfo = `-- name: UpdateContactInfo :one
UPDATE contact_info
SET 
  email = COALESCE($1, email),
  phone = COALESCE($2, phone),
  address = COALESCE($3, address),
  city = COALESCE($4, city),
  state = COALESCE($5, state),
  zip = COALESCE($6, zip),
  country = COALESCE($7, country)
WHERE user_id = $8 AND is_deleted = false
RETURNING id, user_id, email, phone, address, city, state, zip, country, is_deleted, created_at, updated_at, deleted_at
`

type UpdateContactInfoParams struct {
	Email   *string `db:"email" json:"email"`
	Phone   *string `db:"phone" json:"phone"`
	Address *string `db:"address" json:"address"`
	City    *string `db:"city" json:"city"`
	State   *string `db:"state" json:"state"`
	Zip     *string `db:"zip" json:"zip"`
	Country *string `db:"country" json:"country"`
	UserID  int64   `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateContactInfo(ctx context.Context, arg UpdateContactInfoParams) (ContactInfo, error) {
	row := q.db.QueryRow(ctx, updateContactInfo,
		arg.Email,
		arg.Phone,
		arg.Address,
		arg.City,
		arg.State,
		arg.Zip,
		arg.Country,
		arg.UserID,
	)
	var i ContactInfo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Email,
		&i.Phone,
		&i.Address,
		&i.City,
		&i.State,
		&i.Zip,
		&i.Country,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
