// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: education.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEducation = `-- name: CreateEducation :one
INSERT INTO education (
  user_id,
  institution_name,
  institution_logo,
  degree,
  field_of_study,
  start_date,
  end_date,
  is_currently_studying,
  description,
  status,
  display_order,
  duration_years
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, user_id, institution_name, institution_logo, degree, field_of_study, start_date, end_date, is_currently_studying, description, status, display_order, duration_years, is_deleted, created_at, updated_at, deleted_at
`

type CreateEducationParams struct {
	UserID              int64       `db:"user_id" json:"user_id"`
	InstitutionName     string      `db:"institution_name" json:"institution_name"`
	InstitutionLogo     *string     `db:"institution_logo" json:"institution_logo"`
	Degree              string      `db:"degree" json:"degree"`
	FieldOfStudy        *string     `db:"field_of_study" json:"field_of_study"`
	StartDate           pgtype.Date `db:"start_date" json:"start_date"`
	EndDate             pgtype.Date `db:"end_date" json:"end_date"`
	IsCurrentlyStudying bool        `db:"is_currently_studying" json:"is_currently_studying"`
	Description         *string     `db:"description" json:"description"`
	Status              string      `db:"status" json:"status"`
	DisplayOrder        int32       `db:"display_order" json:"display_order"`
	DurationYears       *int32      `db:"duration_years" json:"duration_years"`
}

func (q *Queries) CreateEducation(ctx context.Context, arg CreateEducationParams) (Education, error) {
	row := q.db.QueryRow(ctx, createEducation,
		arg.UserID,
		arg.InstitutionName,
		arg.InstitutionLogo,
		arg.Degree,
		arg.FieldOfStudy,
		arg.StartDate,
		arg.EndDate,
		arg.IsCurrentlyStudying,
		arg.Description,
		arg.Status,
		arg.DisplayOrder,
		arg.DurationYears,
	)
	var i Education
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstitutionName,
		&i.InstitutionLogo,
		&i.Degree,
		&i.FieldOfStudy,
		&i.StartDate,
		&i.EndDate,
		&i.IsCurrentlyStudying,
		&i.Description,
		&i.Status,
		&i.DisplayOrder,
		&i.DurationYears,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getEducationByID = `-- name: GetEducationByID :one
SELECT id, user_id, institution_name, institution_logo, degree, field_of_study, start_date, end_date, is_currently_studying, description, status, display_order, duration_years, is_deleted, created_at, updated_at, deleted_at FROM education
WHERE id = $1 AND is_deleted = false
LIMIT 1
`

func (q *Queries) GetEducationByID(ctx context.Context, id int64) (Education, error) {
	row := q.db.QueryRow(ctx, getEducationByID, id)
	var i Education
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstitutionName,
		&i.InstitutionLogo,
		&i.Degree,
		&i.FieldOfStudy,
		&i.StartDate,
		&i.EndDate,
		&i.IsCurrentlyStudying,
		&i.Description,
		&i.Status,
		&i.DisplayOrder,
		&i.DurationYears,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUserEducation = `-- name: ListUserEducation :many
SELECT id, user_id, institution_name, institution_logo, degree, field_of_study, start_date, end_date, is_currently_studying, description, status, display_order, duration_years, is_deleted, created_at, updated_at, deleted_at FROM education
WHERE user_id = $1 AND is_deleted = false
ORDER BY is_currently_studying DESC, start_date DESC
`

func (q *Queries) ListUserEducation(ctx context.Context, userID int64) ([]Education, error) {
	rows, err := q.db.Query(ctx, listUserEducation, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Education{}
	for rows.Next() {
		var i Education
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.InstitutionName,
			&i.InstitutionLogo,
			&i.Degree,
			&i.FieldOfStudy,
			&i.StartDate,
			&i.EndDate,
			&i.IsCurrentlyStudying,
			&i.Description,
			&i.Status,
			&i.DisplayOrder,
			&i.DurationYears,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteEducation = `-- name: SoftDeleteEducation :exec
UPDATE education
SET is_deleted = true
WHERE id = $1
`

func (q *Queries) SoftDeleteEducation(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteEducation, id)
	return err
}

const updateEducation = `-- name: UpdateEducation :one
UPDATE education
SET 
  institution_name = COALESCE($1, institution_name),
  institution_logo = COALESCE($2, institution_logo),
  degree = COALESCE($3, degree),
  field_of_study = COALESCE($4, field_of_study),
  start_date = COALESCE($5, start_date),
  end_date = $6,
  is_currently_studying = COALESCE($7, is_currently_studying),
  description = COALESCE($8, description),
  status = COALESCE($9, status),
  display_order = COALESCE($10, display_order),
  duration_years = COALESCE($11, duration_years)
WHERE id = $12 AND is_deleted = false
RETURNING id, user_id, institution_name, institution_logo, degree, field_of_study, start_date, end_date, is_currently_studying, description, status, display_order, duration_years, is_deleted, created_at, updated_at, deleted_at
`

type UpdateEducationParams struct {
	InstitutionName     *string           `db:"institution_name" json:"institution_name"`
	InstitutionLogo     *string           `db:"institution_logo" json:"institution_logo"`
	Degree              *string           `db:"degree" json:"degree"`
	FieldOfStudy        *string           `db:"field_of_study" json:"field_of_study"`
	StartDate           pgtype.Date       `db:"start_date" json:"start_date"`
	EndDate             pgtype.Date       `db:"end_date" json:"end_date"`
	IsCurrentlyStudying *bool             `db:"is_currently_studying" json:"is_currently_studying"`
	Description         *string           `db:"description" json:"description"`
	Status              NullContentStatus `db:"status" json:"status"`
	DisplayOrder        *int32            `db:"display_order" json:"display_order"`
	DurationYears       *int32            `db:"duration_years" json:"duration_years"`
	ID                  int64             `db:"id" json:"id"`
}

func (q *Queries) UpdateEducation(ctx context.Context, arg UpdateEducationParams) (Education, error) {
	row := q.db.QueryRow(ctx, updateEducation,
		arg.InstitutionName,
		arg.InstitutionLogo,
		arg.Degree,
		arg.FieldOfStudy,
		arg.StartDate,
		arg.EndDate,
		arg.IsCurrentlyStudying,
		arg.Description,
		arg.Status,
		arg.DisplayOrder,
		arg.DurationYears,
		arg.ID,
	)
	var i Education
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstitutionName,
		&i.InstitutionLogo,
		&i.Degree,
		&i.FieldOfStudy,
		&i.StartDate,
		&i.EndDate,
		&i.IsCurrentlyStudying,
		&i.Description,
		&i.Status,
		&i.DisplayOrder,
		&i.DurationYears,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
