// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: experience.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExperience = `-- name: CreateExperience :one
INSERT INTO experience (
  user_id,
  company_name,
  company_logo,
  position,
  start_date,
  end_date,
  is_currently_working,
  description,
  location,
  status,
  display_order,
  duration_months
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
)
RETURNING id, user_id, company_name, company_logo, position, start_date, end_date, is_currently_working, description, location, status, display_order, duration_months, is_deleted, created_at, updated_at, deleted_at
`

type CreateExperienceParams struct {
	UserID             int64       `db:"user_id" json:"user_id"`
	CompanyName        string      `db:"company_name" json:"company_name"`
	CompanyLogo        *string     `db:"company_logo" json:"company_logo"`
	Position           string      `db:"position" json:"position"`
	StartDate          pgtype.Date `db:"start_date" json:"start_date"`
	EndDate            pgtype.Date `db:"end_date" json:"end_date"`
	IsCurrentlyWorking bool        `db:"is_currently_working" json:"is_currently_working"`
	Description        *string     `db:"description" json:"description"`
	Location           *string     `db:"location" json:"location"`
	Status             string      `db:"status" json:"status"`
	DisplayOrder       int32       `db:"display_order" json:"display_order"`
	DurationMonths     *int32      `db:"duration_months" json:"duration_months"`
}

func (q *Queries) CreateExperience(ctx context.Context, arg CreateExperienceParams) (Experience, error) {
	row := q.db.QueryRow(ctx, createExperience,
		arg.UserID,
		arg.CompanyName,
		arg.CompanyLogo,
		arg.Position,
		arg.StartDate,
		arg.EndDate,
		arg.IsCurrentlyWorking,
		arg.Description,
		arg.Location,
		arg.Status,
		arg.DisplayOrder,
		arg.DurationMonths,
	)
	var i Experience
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyName,
		&i.CompanyLogo,
		&i.Position,
		&i.StartDate,
		&i.EndDate,
		&i.IsCurrentlyWorking,
		&i.Description,
		&i.Location,
		&i.Status,
		&i.DisplayOrder,
		&i.DurationMonths,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCurrentExperience = `-- name: GetCurrentExperience :many
SELECT id, user_id, company_name, company_logo, position, start_date, end_date, is_currently_working, description, location, status, display_order, duration_months, is_deleted, created_at, updated_at, deleted_at FROM experience
WHERE user_id = $1 AND is_currently_working = true AND is_deleted = false
ORDER BY start_date DESC
`

func (q *Queries) GetCurrentExperience(ctx context.Context, userID int64) ([]Experience, error) {
	rows, err := q.db.Query(ctx, getCurrentExperience, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Experience{}
	for rows.Next() {
		var i Experience
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CompanyName,
			&i.CompanyLogo,
			&i.Position,
			&i.StartDate,
			&i.EndDate,
			&i.IsCurrentlyWorking,
			&i.Description,
			&i.Location,
			&i.Status,
			&i.DisplayOrder,
			&i.DurationMonths,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExperienceByID = `-- name: GetExperienceByID :one
SELECT id, user_id, company_name, company_logo, position, start_date, end_date, is_currently_working, description, location, status, display_order, duration_months, is_deleted, created_at, updated_at, deleted_at FROM experience
WHERE id = $1 AND is_deleted = false
LIMIT 1
`

func (q *Queries) GetExperienceByID(ctx context.Context, id int64) (Experience, error) {
	row := q.db.QueryRow(ctx, getExperienceByID, id)
	var i Experience
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyName,
		&i.CompanyLogo,
		&i.Position,
		&i.StartDate,
		&i.EndDate,
		&i.IsCurrentlyWorking,
		&i.Description,
		&i.Location,
		&i.Status,
		&i.DisplayOrder,
		&i.DurationMonths,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUserExperience = `-- name: ListUserExperience :many
SELECT id, user_id, company_name, company_logo, position, start_date, end_date, is_currently_working, description, location, status, display_order, duration_months, is_deleted, created_at, updated_at, deleted_at FROM experience
WHERE user_id = $1 AND is_deleted = false
ORDER BY is_currently_working DESC, start_date DESC
`

func (q *Queries) ListUserExperience(ctx context.Context, userID int64) ([]Experience, error) {
	rows, err := q.db.Query(ctx, listUserExperience, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Experience{}
	for rows.Next() {
		var i Experience
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CompanyName,
			&i.CompanyLogo,
			&i.Position,
			&i.StartDate,
			&i.EndDate,
			&i.IsCurrentlyWorking,
			&i.Description,
			&i.Location,
			&i.Status,
			&i.DisplayOrder,
			&i.DurationMonths,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteExperience = `-- name: SoftDeleteExperience :exec
UPDATE experience
SET is_deleted = true
WHERE id = $1
`

func (q *Queries) SoftDeleteExperience(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteExperience, id)
	return err
}

const updateExperience = `-- name: UpdateExperience :one
UPDATE experience
SET 
  company_name = COALESCE($1, company_name),
  company_logo = COALESCE($2, company_logo),
  position = COALESCE($3, position),
  start_date = COALESCE($4, start_date),
  end_date = $5,
  is_currently_working = COALESCE($6, is_currently_working),
  description = COALESCE($7, description),
  location = COALESCE($8, location),
  status = COALESCE($9, status),
  display_order = COALESCE($10, display_order),
  duration_months = COALESCE($11, duration_months)
WHERE id = $12 AND is_deleted = false
RETURNING id, user_id, company_name, company_logo, position, start_date, end_date, is_currently_working, description, location, status, display_order, duration_months, is_deleted, created_at, updated_at, deleted_at
`

type UpdateExperienceParams struct {
	CompanyName        *string           `db:"company_name" json:"company_name"`
	CompanyLogo        *string           `db:"company_logo" json:"company_logo"`
	Position           *string           `db:"position" json:"position"`
	StartDate          pgtype.Date       `db:"start_date" json:"start_date"`
	EndDate            pgtype.Date       `db:"end_date" json:"end_date"`
	IsCurrentlyWorking *bool             `db:"is_currently_working" json:"is_currently_working"`
	Description        *string           `db:"description" json:"description"`
	Location           *string           `db:"location" json:"location"`
	Status             NullContentStatus `db:"status" json:"status"`
	DisplayOrder       *int32            `db:"display_order" json:"display_order"`
	DurationMonths     *int32            `db:"duration_months" json:"duration_months"`
	ID                 int64             `db:"id" json:"id"`
}

func (q *Queries) UpdateExperience(ctx context.Context, arg UpdateExperienceParams) (Experience, error) {
	row := q.db.QueryRow(ctx, updateExperience,
		arg.CompanyName,
		arg.CompanyLogo,
		arg.Position,
		arg.StartDate,
		arg.EndDate,
		arg.IsCurrentlyWorking,
		arg.Description,
		arg.Location,
		arg.Status,
		arg.DisplayOrder,
		arg.DurationMonths,
		arg.ID,
	)
	var i Experience
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CompanyName,
		&i.CompanyLogo,
		&i.Position,
		&i.StartDate,
		&i.EndDate,
		&i.IsCurrentlyWorking,
		&i.Description,
		&i.Location,
		&i.Status,
		&i.DisplayOrder,
		&i.DurationMonths,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
