// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: experience_skills.sql

package db

import (
	"context"
)

const addExperienceSkill = `-- name: AddExperienceSkill :exec
INSERT INTO experience_skills (experience_id, skill_id)
VALUES ($1, $2)
ON CONFLICT (experience_id, skill_id) DO NOTHING
`

type AddExperienceSkillParams struct {
	ExperienceID int64 `db:"experience_id" json:"experience_id"`
	SkillID      int64 `db:"skill_id" json:"skill_id"`
}

func (q *Queries) AddExperienceSkill(ctx context.Context, arg AddExperienceSkillParams) error {
	_, err := q.db.Exec(ctx, addExperienceSkill, arg.ExperienceID, arg.SkillID)
	return err
}

const getExperienceSkills = `-- name: GetExperienceSkills :many
SELECT s.id, s.user_id, s.category_id, s.name, s.proficiency, s.icon, s.status, s.display_order, s.usage_count, s.is_deleted, s.created_at, s.updated_at, s.deleted_at FROM skills s
INNER JOIN experience_skills es ON s.id = es.skill_id
WHERE es.experience_id = $1 AND es.is_deleted = false AND s.is_deleted = false
ORDER BY s.name
`

func (q *Queries) GetExperienceSkills(ctx context.Context, experienceID int64) ([]Skill, error) {
	rows, err := q.db.Query(ctx, getExperienceSkills, experienceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Skill{}
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.Name,
			&i.Proficiency,
			&i.Icon,
			&i.Status,
			&i.DisplayOrder,
			&i.UsageCount,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeExperienceSkill = `-- name: RemoveExperienceSkill :exec
UPDATE experience_skills
SET is_deleted = true
WHERE experience_id = $1 AND skill_id = $2
`

type RemoveExperienceSkillParams struct {
	ExperienceID int64 `db:"experience_id" json:"experience_id"`
	SkillID      int64 `db:"skill_id" json:"skill_id"`
}

func (q *Queries) RemoveExperienceSkill(ctx context.Context, arg RemoveExperienceSkillParams) error {
	_, err := q.db.Exec(ctx, removeExperienceSkill, arg.ExperienceID, arg.SkillID)
	return err
}
