// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type User struct {
	ID          int64  `json:"id"`
	Email       string `json:"email"`
	Preferences []byte `json:"preferences"`
}
