// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: project_images.sql

package db

import (
	"context"
)

const createProjectImage = `-- name: CreateProjectImage :one
INSERT INTO project_images (
  project_id,
  image_url,
  caption,
  display_order
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, project_id, image_url, caption, display_order, is_deleted, created_at, deleted_at
`

type CreateProjectImageParams struct {
	ProjectID    int64   `db:"project_id" json:"project_id"`
	ImageUrl     string  `db:"image_url" json:"image_url"`
	Caption      *string `db:"caption" json:"caption"`
	DisplayOrder int32   `db:"display_order" json:"display_order"`
}

func (q *Queries) CreateProjectImage(ctx context.Context, arg CreateProjectImageParams) (ProjectImage, error) {
	row := q.db.QueryRow(ctx, createProjectImage,
		arg.ProjectID,
		arg.ImageUrl,
		arg.Caption,
		arg.DisplayOrder,
	)
	var i ProjectImage
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.ImageUrl,
		&i.Caption,
		&i.DisplayOrder,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getProjectImages = `-- name: GetProjectImages :many
SELECT id, project_id, image_url, caption, display_order, is_deleted, created_at, deleted_at FROM project_images
WHERE project_id = $1 AND is_deleted = false
ORDER BY display_order ASC
`

func (q *Queries) GetProjectImages(ctx context.Context, projectID int64) ([]ProjectImage, error) {
	rows, err := q.db.Query(ctx, getProjectImages, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectImage{}
	for rows.Next() {
		var i ProjectImage
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ImageUrl,
			&i.Caption,
			&i.DisplayOrder,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProjectImage = `-- name: SoftDeleteProjectImage :exec
UPDATE project_images
SET is_deleted = true
WHERE id = $1
`

func (q *Queries) SoftDeleteProjectImage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteProjectImage, id)
	return err
}

const updateProjectImageOrder = `-- name: UpdateProjectImageOrder :exec
UPDATE project_images
SET display_order = $2
WHERE id = $1
`

type UpdateProjectImageOrderParams struct {
	ID           int64 `db:"id" json:"id"`
	DisplayOrder int32 `db:"display_order" json:"display_order"`
}

func (q *Queries) UpdateProjectImageOrder(ctx context.Context, arg UpdateProjectImageOrderParams) error {
	_, err := q.db.Exec(ctx, updateProjectImageOrder, arg.ID, arg.DisplayOrder)
	return err
}
