// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddExperienceSkill(ctx context.Context, arg AddExperienceSkillParams) error
	AddProjectTag(ctx context.Context, arg AddProjectTagParams) error
	CreateContactInfo(ctx context.Context, arg CreateContactInfoParams) (ContactInfo, error)
	CreateEducation(ctx context.Context, arg CreateEducationParams) (Education, error)
	CreateExperience(ctx context.Context, arg CreateExperienceParams) (Experience, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateProjectImage(ctx context.Context, arg CreateProjectImageParams) (ProjectImage, error)
	CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error)
	CreateSocialLink(ctx context.Context, arg CreateSocialLinkParams) (SocialLink, error)
	CreateTag(ctx context.Context, arg CreateTagParams) (Tag, error)
	CreateTestimonial(ctx context.Context, arg CreateTestimonialParams) (Testimonial, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DecrementProjectImageCount(ctx context.Context, id int64) error
	DecrementProjectTagCount(ctx context.Context, id int64) error
	DecrementSkillUsage(ctx context.Context, id int64) error
	GetCurrentExperience(ctx context.Context, userID int64) ([]Experience, error)
	GetEducationByID(ctx context.Context, id int64) (Education, error)
	GetExperienceByID(ctx context.Context, id int64) (Experience, error)
	GetExperienceSkills(ctx context.Context, experienceID int64) ([]Skill, error)
	GetOrCreateTag(ctx context.Context, arg GetOrCreateTagParams) (Tag, error)
	// ===========================================
	// sql/queries/projects.sql
	// ===========================================
	GetProjectByID(ctx context.Context, id int64) (Project, error)
	GetProjectBySlug(ctx context.Context, arg GetProjectBySlugParams) (Project, error)
	GetProjectImages(ctx context.Context, projectID int64) ([]ProjectImage, error)
	GetProjectTags(ctx context.Context, projectID int64) ([]Tag, error)
	GetProjectsByTag(ctx context.Context, tagID int64) ([]Project, error)
	GetSkillByID(ctx context.Context, id int64) (Skill, error)
	GetSocialLinkByPlatform(ctx context.Context, arg GetSocialLinkByPlatformParams) (SocialLink, error)
	GetTagByID(ctx context.Context, id int64) (Tag, error)
	GetTagBySlug(ctx context.Context, slug string) (Tag, error)
	GetTestimonialByID(ctx context.Context, id int64) (Testimonial, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByFirebaseUID(ctx context.Context, firebaseUid string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserContactInfo(ctx context.Context, userID int64) (ContactInfo, error)
	GetUserSocialLinks(ctx context.Context, userID int64) ([]SocialLink, error)
	IncrementProjectImageCount(ctx context.Context, id int64) error
	IncrementProjectTagCount(ctx context.Context, id int64) error
	IncrementSkillUsage(ctx context.Context, id int64) error
	ListFeaturedProjects(ctx context.Context, arg ListFeaturedProjectsParams) ([]Project, error)
	ListProjectTestimonials(ctx context.Context, projectID *int64) ([]Testimonial, error)
	ListProjectsByStatus(ctx context.Context, arg ListProjectsByStatusParams) ([]Project, error)
	ListTags(ctx context.Context) ([]Tag, error)
	ListTopSkills(ctx context.Context, arg ListTopSkillsParams) ([]Skill, error)
	ListUserEducation(ctx context.Context, userID int64) ([]Education, error)
	ListUserExperience(ctx context.Context, userID int64) ([]Experience, error)
	ListUserProjects(ctx context.Context, userID int64) ([]Project, error)
	ListUserSkills(ctx context.Context, userID int64) ([]ListUserSkillsRow, error)
	ListUserSkillsByCategory(ctx context.Context, arg ListUserSkillsByCategoryParams) ([]Skill, error)
	ListUserTestimonials(ctx context.Context, userID int64) ([]Testimonial, error)
	RemoveExperienceSkill(ctx context.Context, arg RemoveExperienceSkillParams) error
	RemoveProjectTag(ctx context.Context, arg RemoveProjectTagParams) error
	RestoreUser(ctx context.Context, id int64) error
	SoftDeleteEducation(ctx context.Context, id int64) error
	SoftDeleteExperience(ctx context.Context, id int64) error
	SoftDeleteProject(ctx context.Context, id int64) error
	SoftDeleteProjectImage(ctx context.Context, id int64) error
	SoftDeleteSkill(ctx context.Context, id int64) error
	SoftDeleteSocialLink(ctx context.Context, id int64) error
	SoftDeleteTestimonial(ctx context.Context, id int64) error
	SoftDeleteUser(ctx context.Context, id int64) error
	UpdateContactInfo(ctx context.Context, arg UpdateContactInfoParams) (ContactInfo, error)
	UpdateEducation(ctx context.Context, arg UpdateEducationParams) (Education, error)
	UpdateExperience(ctx context.Context, arg UpdateExperienceParams) (Experience, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateProjectImageOrder(ctx context.Context, arg UpdateProjectImageOrderParams) error
	UpdateSkill(ctx context.Context, arg UpdateSkillParams) (Skill, error)
	UpdateSocialLink(ctx context.Context, arg UpdateSocialLinkParams) (SocialLink, error)
	UpdateTestimonial(ctx context.Context, arg UpdateTestimonialParams) (Testimonial, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
}

var _ Querier = (*Queries)(nil)
