// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: social_links.sql

package db

import (
	"context"
)

const createSocialLink = `-- name: CreateSocialLink :one
INSERT INTO social_links (
  user_id,
  platform,
  url,
  display_order
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, user_id, platform, url, display_order, is_deleted, created_at, updated_at, deleted_at
`

type CreateSocialLinkParams struct {
	UserID       int64  `db:"user_id" json:"user_id"`
	Platform     string `db:"platform" json:"platform"`
	Url          string `db:"url" json:"url"`
	DisplayOrder int32  `db:"display_order" json:"display_order"`
}

func (q *Queries) CreateSocialLink(ctx context.Context, arg CreateSocialLinkParams) (SocialLink, error) {
	row := q.db.QueryRow(ctx, createSocialLink,
		arg.UserID,
		arg.Platform,
		arg.Url,
		arg.DisplayOrder,
	)
	var i SocialLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Url,
		&i.DisplayOrder,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSocialLinkByPlatform = `-- name: GetSocialLinkByPlatform :one
SELECT id, user_id, platform, url, display_order, is_deleted, created_at, updated_at, deleted_at FROM social_links
WHERE user_id = $1 AND platform = $2 AND is_deleted = false
LIMIT 1
`

type GetSocialLinkByPlatformParams struct {
	UserID   int64  `db:"user_id" json:"user_id"`
	Platform string `db:"platform" json:"platform"`
}

func (q *Queries) GetSocialLinkByPlatform(ctx context.Context, arg GetSocialLinkByPlatformParams) (SocialLink, error) {
	row := q.db.QueryRow(ctx, getSocialLinkByPlatform, arg.UserID, arg.Platform)
	var i SocialLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Url,
		&i.DisplayOrder,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserSocialLinks = `-- name: GetUserSocialLinks :many
SELECT id, user_id, platform, url, display_order, is_deleted, created_at, updated_at, deleted_at FROM social_links
WHERE user_id = $1 AND is_deleted = false
ORDER BY display_order ASC
`

func (q *Queries) GetUserSocialLinks(ctx context.Context, userID int64) ([]SocialLink, error) {
	rows, err := q.db.Query(ctx, getUserSocialLinks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SocialLink{}
	for rows.Next() {
		var i SocialLink
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Platform,
			&i.Url,
			&i.DisplayOrder,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteSocialLink = `-- name: SoftDeleteSocialLink :exec
UPDATE social_links
SET is_deleted = true
WHERE id = $1
`

func (q *Queries) SoftDeleteSocialLink(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteSocialLink, id)
	return err
}

const updateSocialLink = `-- name: UpdateSocialLink :one
UPDATE social_links
SET 
  url = COALESCE($1, url),
  display_order = COALESCE($2, display_order)
WHERE id = $3 AND is_deleted = false
RETURNING id, user_id, platform, url, display_order, is_deleted, created_at, updated_at, deleted_at
`

type UpdateSocialLinkParams struct {
	Url          *string `db:"url" json:"url"`
	DisplayOrder *int32  `db:"display_order" json:"display_order"`
	ID           int64   `db:"id" json:"id"`
}

func (q *Queries) UpdateSocialLink(ctx context.Context, arg UpdateSocialLinkParams) (SocialLink, error) {
	row := q.db.QueryRow(ctx, updateSocialLink, arg.Url, arg.DisplayOrder, arg.ID)
	var i SocialLink
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Platform,
		&i.Url,
		&i.DisplayOrder,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
