// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: testimonials.sql

package db

import (
	"context"
)

const createTestimonial = `-- name: CreateTestimonial :one
INSERT INTO testimonials (
  user_id,
  client_name,
  client_position,
  client_company,
  client_photo,
  content,
  rating,
  project_id,
  status,
  display_order
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, user_id, client_name, client_position, client_company, client_photo, content, rating, project_id, status, display_order, is_deleted, created_at, updated_at, deleted_at
`

type CreateTestimonialParams struct {
	UserID         int64   `db:"user_id" json:"user_id"`
	ClientName     string  `db:"client_name" json:"client_name"`
	ClientPosition *string `db:"client_position" json:"client_position"`
	ClientCompany  *string `db:"client_company" json:"client_company"`
	ClientPhoto    *string `db:"client_photo" json:"client_photo"`
	Content        string  `db:"content" json:"content"`
	Rating         *int32  `db:"rating" json:"rating"`
	ProjectID      *int64  `db:"project_id" json:"project_id"`
	Status         string  `db:"status" json:"status"`
	DisplayOrder   int32   `db:"display_order" json:"display_order"`
}

func (q *Queries) CreateTestimonial(ctx context.Context, arg CreateTestimonialParams) (Testimonial, error) {
	row := q.db.QueryRow(ctx, createTestimonial,
		arg.UserID,
		arg.ClientName,
		arg.ClientPosition,
		arg.ClientCompany,
		arg.ClientPhoto,
		arg.Content,
		arg.Rating,
		arg.ProjectID,
		arg.Status,
		arg.DisplayOrder,
	)
	var i Testimonial
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientName,
		&i.ClientPosition,
		&i.ClientCompany,
		&i.ClientPhoto,
		&i.Content,
		&i.Rating,
		&i.ProjectID,
		&i.Status,
		&i.DisplayOrder,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTestimonialByID = `-- name: GetTestimonialByID :one
SELECT id, user_id, client_name, client_position, client_company, client_photo, content, rating, project_id, status, display_order, is_deleted, created_at, updated_at, deleted_at FROM testimonials
WHERE id = $1 AND is_deleted = false
LIMIT 1
`

func (q *Queries) GetTestimonialByID(ctx context.Context, id int64) (Testimonial, error) {
	row := q.db.QueryRow(ctx, getTestimonialByID, id)
	var i Testimonial
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientName,
		&i.ClientPosition,
		&i.ClientCompany,
		&i.ClientPhoto,
		&i.Content,
		&i.Rating,
		&i.ProjectID,
		&i.Status,
		&i.DisplayOrder,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listProjectTestimonials = `-- name: ListProjectTestimonials :many
SELECT id, user_id, client_name, client_position, client_company, client_photo, content, rating, project_id, status, display_order, is_deleted, created_at, updated_at, deleted_at FROM testimonials
WHERE project_id = $1 AND is_deleted = false
ORDER BY rating DESC, created_at DESC
`

func (q *Queries) ListProjectTestimonials(ctx context.Context, projectID *int64) ([]Testimonial, error) {
	rows, err := q.db.Query(ctx, listProjectTestimonials, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Testimonial{}
	for rows.Next() {
		var i Testimonial
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ClientName,
			&i.ClientPosition,
			&i.ClientCompany,
			&i.ClientPhoto,
			&i.Content,
			&i.Rating,
			&i.ProjectID,
			&i.Status,
			&i.DisplayOrder,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserTestimonials = `-- name: ListUserTestimonials :many
SELECT id, user_id, client_name, client_position, client_company, client_photo, content, rating, project_id, status, display_order, is_deleted, created_at, updated_at, deleted_at FROM testimonials
WHERE user_id = $1 AND is_deleted = false
ORDER BY rating DESC, created_at DESC
`

func (q *Queries) ListUserTestimonials(ctx context.Context, userID int64) ([]Testimonial, error) {
	rows, err := q.db.Query(ctx, listUserTestimonials, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Testimonial{}
	for rows.Next() {
		var i Testimonial
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ClientName,
			&i.ClientPosition,
			&i.ClientCompany,
			&i.ClientPhoto,
			&i.Content,
			&i.Rating,
			&i.ProjectID,
			&i.Status,
			&i.DisplayOrder,
			&i.IsDeleted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTestimonial = `-- name: SoftDeleteTestimonial :exec
UPDATE testimonials
SET is_deleted = true
WHERE id = $1
`

func (q *Queries) SoftDeleteTestimonial(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteTestimonial, id)
	return err
}

const updateTestimonial = `-- name: UpdateTestimonial :one
UPDATE testimonials
SET 
  client_name = COALESCE($1, client_name),
  client_position = COALESCE($2, client_position),
  client_company = COALESCE($3, client_company),
  client_photo = COALESCE($4, client_photo),
  content = COALESCE($5, content),
  rating = COALESCE($6, rating),
  project_id = $7,
  status = COALESCE($8, status),
  display_order = COALESCE($9, display_order)
WHERE id = $10 AND is_deleted = false
RETURNING id, user_id, client_name, client_position, client_company, client_photo, content, rating, project_id, status, display_order, is_deleted, created_at, updated_at, deleted_at
`

type UpdateTestimonialParams struct {
	ClientName     *string           `db:"client_name" json:"client_name"`
	ClientPosition *string           `db:"client_position" json:"client_position"`
	ClientCompany  *string           `db:"client_company" json:"client_company"`
	ClientPhoto    *string           `db:"client_photo" json:"client_photo"`
	Content        *string           `db:"content" json:"content"`
	Rating         *int32            `db:"rating" json:"rating"`
	ProjectID      *int64            `db:"project_id" json:"project_id"`
	Status         NullContentStatus `db:"status" json:"status"`
	DisplayOrder   *int32            `db:"display_order" json:"display_order"`
	ID             int64             `db:"id" json:"id"`
}

func (q *Queries) UpdateTestimonial(ctx context.Context, arg UpdateTestimonialParams) (Testimonial, error) {
	row := q.db.QueryRow(ctx, updateTestimonial,
		arg.ClientName,
		arg.ClientPosition,
		arg.ClientCompany,
		arg.ClientPhoto,
		arg.Content,
		arg.Rating,
		arg.ProjectID,
		arg.Status,
		arg.DisplayOrder,
		arg.ID,
	)
	var i Testimonial
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ClientName,
		&i.ClientPosition,
		&i.ClientCompany,
		&i.ClientPhoto,
		&i.Content,
		&i.Rating,
		&i.ProjectID,
		&i.Status,
		&i.DisplayOrder,
		&i.IsDeleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
